set(_CATKIN_CURRENT_PACKAGE "global_fusion")
set(global_fusion_VERSION "0.0.0")
set(global_fusion_MAINTAINER "tony-ws1 <tony-ws1@todo.todo>")
set(global_fusion_PACKAGE_FORMAT "2")
set(global_fusion_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(global_fusion_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(global_fusion_BUILDTOOL_DEPENDS "catkin")
set(global_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(global_fusion_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(global_fusion_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(global_fusion_TEST_DEPENDS )
set(global_fusion_DOC_DEPENDS )
set(global_fusion_URL_WEBSITE "")
set(global_fusion_URL_BUGTRACKER "")
set(global_fusion_URL_REPOSITORY "")
set(global_fusion_DEPRECATED "")