set(_CATKIN_CURRENT_PACKAGE "camera_models")
set(camera_models_VERSION "0.0.0")
set(camera_models_MAINTAINER "dvorak <dvorak@todo.todo>")
set(camera_models_PACKAGE_FORMAT "1")
set(camera_models_BUILD_DEPENDS "roscpp" "std_msgs")
set(camera_models_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(camera_models_BUILDTOOL_DEPENDS "catkin")
set(camera_models_BUILDTOOL_EXPORT_DEPENDS )
set(camera_models_EXEC_DEPENDS "roscpp" "std_msgs")
set(camera_models_RUN_DEPENDS "roscpp" "std_msgs")
set(camera_models_TEST_DEPENDS )
set(camera_models_DOC_DEPENDS )
set(camera_models_URL_WEBSITE "")
set(camera_models_URL_BUGTRACKER "")
set(camera_models_URL_REPOSITORY "")
set(camera_models_DEPRECATED "")